config/routes.rb
Rails.application.routes.draw do
  get 'messages/index'
  devise_for :users
  root to: 'codes#index'
  resources :codes do
    resources :comments, only: :create
  end
  resources :profiles, only: %i[show edit update]
    resources :mypages, only: :show 
    resources :rooms, only: %i[index new create destroy] do
    resources :messages, only: %i[index show create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/code.rb
class Code < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :comments

  with_options presence: true do
    validates :image
    validates :message
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :code
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  belongs_to :user
  has_one_attached :image

  validates :content, presence: true, unless: :was_attached?

  def was_attached?
    image.attached?
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_users, dependent: :destroy
  has_many :users, through: :room_users
  has_many :messages, dependent: :destroy
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { maximum: 6 }
  validates :birthday, { length: { maximum: 10 } }
  validates :favorite_brand, { length: { maximum: 40 } }
  validates :comment, { length: { maximum: 40 } }
  has_many :codes
  has_many :comments
  has_many :messages, dependent: :destroy
  has_many :room_users
  has_many :rooms, through: :room_users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/codes_controller.rb
class CodesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit]
  before_action :set_code, only: [:edit, :show, :update, :destroy]

  def index
    @code = Code.all.order('created_at DESC')
  end

  def new
    @code = Code.new
  end

  def create
    @code = Code.new(code_params)
    if @code.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @code.comments.includes(:user)
  end

  def edit
  end

  def update
    @code.update(code_params)
    if @code.save
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    redirect_to root_path if @code.destroy
  end

  private

  def code_params
    params.require(:code).permit(:image, :message, :code_title, :brand_name).merge(user_id: current_user.id)
  end

  def set_code
    @code = Code.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: :create

  def create
    Comment.create(comment_params)
    redirect_to root_path
  end

  private

  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, code_id: params[:code_id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!, only: %i[index create show]

  def index
    @message = Message.new
    @room = Room.find(params[:room_id])
    @messages = @room.messages.includes(:user)
  end

  def show
    user = User.find(params[:id])
    @name = user.name
    @codes = user.codes
  end

  def create
    @room = Room.find(params[:room_id])
    @message = @room.messages.new(message_params)
    if @message.save
      redirect_to room_messages_path(@room)
    else
      @messages = @room.messages.includes(:user)
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end
end

app/controllers/mypages_controller.rb
class MypagesController < ApplicationController
  before_action :authenticate_user!, only: :show

  def show
    user = User.find(params[:id])
    @id = user.id
    @name = user.name
    @codes = user.codes
    @birthday = user.birthday
    @favorite_brand = user.favorite_brand
    @comment = user.comment
    @twitter = user.twitter
    @instagram = user.instagram
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!, only: %i[update edit]
  before_action :set_params, only: %i[update edit show]

  def edit
  end

  def show
  end

  def update
    @user.update(user_params)
    if @user.save
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :birthday, :favorite_brand, :comment, :twitter, :instagram)
  end

  def set_params
    @user = User.find(params[:id])
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!, only: %i[index new create destroy]

  def index
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to room_messages_path(@room.id)
    else
      render :new
    end
  end

  def show
    @name = user.name
  end

  def destroy
    room = Room.find(params[:id])
    room.destroy
    redirect_to root_path
  end

  private

  def room_params
    params.require(:room).permit(user_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/codes_helper.rb
module CodesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/mypages_helper.rb
module MypagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  # def edit
  # @user = User.find(current_user.id)
  # end

  # def update
  # @user = User.find(current_user.id)
  # if @user.update(user_params)
  # redirect_to profile_path, success: t('defaults.message.edited', item: User.model_name.human)
  # else
  # flash.now['danger'] = t('defaults.message.not_edited', item: User.model_name.human)
  # render :edit
  # end
  # end

  # private

  # def user_params
  # params.require(:user).permit(:email, :first_name, :last_name, :avatar)
  # end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/codes/edit.html.erb
<div class="codes-post-contents">
  <header class="codes-post-header">
    <%= image_tag "logo.PNG", size: '180x60',class:"logo-icon" %>

  </header>
    <div class="codes-post-main">
      <%= form_with model: @code, local: true do |f| %>

    <%= render 'devise/shared/error_messages', model: f.object %>

    <div class="code-upload">
      <div class="code-topic">
        post correction
      </div>
        <div class="click-upload">
          <p>
            クリックしてコーデをアップロード
              <span class="indispensable">＊</span>
          </p>
            <%= f.file_field :image, id:"code-image" %>
      </div>
    </div>

    <div class="codes-explain">
        <div class="code-title-text">
          <p> コーディネートについて
            <span class="indispensable">＊</span>
          </p>
        </div>
          <%= f.text_area :message, class:"code-message", id:"code-info", placeholder:"何か書く...", maxlength:"1000" %>
    </div>

    <div class="code-uesr-detail">
        <div class="form-datail">
          <div class="code-title-detail">
            コーデタイトル
          </div>
        <div>
          <%= f.text_area :code_title, class:"code-text", id:"code-info" %>
      </div>
      <div class="brand-detail">
            着用ブランド
          </div>
        <div>
          <%= f.text_area :brand_name, class:"code-text", id:"code-info" %>
      </div>
    </div>
    <div class="post-btn-contents">
      <%= f.submit "変更する", class:"correction-btn" %>
      <%=link_to 'もどる',code_path(@code.id) , class:"back-btn" %>
    </div>
    <div>
      <audio autoplay src="https://res.cloudinary.com/dr47riclr/video/upload/v1629117741/music/Gm_Code1_tlp363.mp3"></audio>
    </div>
  </div>
</div>
  <% end %>
</div>

app/views/codes/index.html.erb
<%= render "devise/shared/header" %>
<div class='main'>

  <div class='title-contents'>
    <p class="btn"><a onClick="sound()">Gm Code</a></p>

    <audio id="sound" preload="auto">
	  <source src="https://res.cloudinary.com/dr47riclr/video/upload/v1628663126/music/%E5%B0%8F%E9%87%8E%E3%81%A1%E3%82%83%E3%82%93%E5%84%AA%E3%81%97%E3%81%95_txlboe.mp3" type="audio/mp3">
    </audio>
    
      <p class='service-explain'>
        お気に入りのコーデをシェアしよう!
      </p>
    </div>

    <div class='code-contents'>
      <h3 class='title'>New Code</h3>
        <div class="grad-wrap">
          <input id="trigger1" class="grad-trigger" type="checkbox">
          <label class="grad-btn" for="trigger1"></label>
        <div class="grad-item">
      <ul class='code-lists'>

      <% @code.each do|code| %>
        
      <li class='list'>
        <%= link_to code_path(code.id) do %>
        
        <div class='code-img-content'>
          <%= image_tag code.image, class: "code-img" if code.image.attached? %>
       </div>
        <% end %>
      <% end %>

    <% if @code.blank? %>
      <li class='list'>
        <%= image_tag "title.PNG", class: "code-img" %>
          <h3 class='item-name'>
            コーディネートを投稿しよう！
          </h3>
        <% end %>
      </ul>
    <div class="list-btn">
    </div>
  </div>
</div>

    <%= link_to(new_code_path, class: 'code-btn') do %>
  <span class='code-btn-text'>post code</span>
  <%= image_tag 'camera.png' , size: '100x55' ,class: "code-btn-icon" %>
<% end %>

  <div class='announces'>
    <h3 class='announces-title'>お知らせ</h3>
    </div>

  <table class="table">
    <tbody>
      <div class='announces'>
      <tr>
        <th class='announce-date'>2021/08/23</th>
        <td class='announce'>プロフィール機能を実装しました。</td>
        </tr>
      </div>
      
      <div class='announces'>
      <tr>
        <th class='announce-date'>2021/08/19</th>
        <td class='announce'>コメント機能を実装しました。</td>
      </tr>
      </div>

      <div class='announces'>
      <tr>
        <th class='announce-date'>2021/08/15</th>
        <td class='announce'>Gm_Codeのショートムービーが完成しました！</td>
      </tr>
      </div>
    </tbody>
  </table>

      <div class='movie-announce'>動画はこちらから</div>

   <video controls width="500" height="360" src="https://res.cloudinary.com/dr47riclr/video/upload/v1630031348/music/%E3%82%A2%E3%83%95%E3%82%9A%E3%83%AA%E7%B4%B9%E4%BB%8B%E5%8B%95%E7%94%BB_n2xadj.mp4"></video>
      <div>
      <audio  autoplay  src="https://res.cloudinary.com/dr47riclr/video/upload/v1628738609/music/Gm1_dzomgg.mp3"></audio>
    </div>
  <%= render "devise/shared/footer" %>

app/views/codes/new.html.erb
<div class="codes-post-contents">
  <header class="codes-post-header">
    <%= image_tag "logo.PNG", size: '180x60',class:"logo-icon" %>

  </header>
    <div class="codes-post-main">
      <%= form_with model: @code, local: true do |f| %>

    <%= render 'devise/shared/error_messages', model: f.object %>

    <div class="code-upload">
      <div class="code-topic">
        new post
      </div>
        <div class="click-upload">
          <p>
            クリックしてコーデをアップロード
              <span class="indispensable">＊</span>
          </p>
            <%= f.file_field :image, id:"code-image" %>
      </div>
    </div>

    <div class="codes-explain">
        <div class="code-title-text">
          <p> コーディネートについて
            <span class="indispensable">＊</span>
          </p>
        </div>
          <%= f.text_area :message, class:"code-message", id:"code-info", placeholder:"何か書く...", maxlength:"1000" %>
    </div>

    <div class="code-uesr-detail">
        <div class="form-detail">
          <div class="code-title-detail">
            コーデタイトル
          </div>
        <div>
          <%= f.text_area :code_title, class:"code-text", id:"code-info" %>
      </div>
      <div class="brand-detail">
            着用ブランド
          </div>
        <div>
          <%= f.text_area :brand_name, class:"code-text", id:"code-info" %>
      </div>
    </div>
    <div class="post-btn-contents">
      <%= f.submit "投稿する" ,class:"post-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <div>
      <audio autoplay src="https://res.cloudinary.com/dr47riclr/video/upload/v1628738609/music/Gm2_hhmzaj.mp3"></audio>
    </div>
  </div>
</div>
  <% end %>
</div>

app/views/codes/show.html.erb
<%= render "devise/shared/header" %>

<div class="code-show">
  <div class="code-box">
    <h3 class="code-explain-box">
      user :
     <span class="name">
     <%= link_to @code.user.name, mypage_path(@code.user.id), method: :get, class: "code-mypage-btn" %>
      </a>
    </span>
    </h3>
      <div class="code-img-content">
        <%= image_tag @code.image ,class:"code-box-img" %>
      </div>

      <% if user_signed_in? && current_user.id == @code.user_id %>
        <%= link_to "投稿の編集", edit_code_path(@code.id), method: :get, class: "code-blue-btn" %>
        <%= link_to "削除", code_path(@code.id), method: :delete, class:"code-destroy" %>
      <% end %>

      <h3 class="code-explain-box">＜コーデタイトル＞
        <%= simple_format @code.code_title %>
      </h3>

      <div class="code-explain-box">＜メッセージ＞
        <%= simple_format @code.message %>
      </div>

      <div class="code-explain-box">＜着用ブランド＞
        <%= simple_format @code.brand_name %>
      </div>


    <div class="comment-box">
      <% if user_signed_in? %>
        <%= form_with(model: [@code, @comment], local: true) do |f| %>
          <%= f.text_area :text, class:"comment-text", rows: "2" %>
          <button type="submit" class="comment-btn">
          <span>コメントする<span>
        </button>
        <% end %>
      <% else %>
        <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p>
        </strong>
      <% end %>
      <div class="comments">
        <h3>＜コメント一覧＞</h3>
        <% @comments.each do |comment| %>
          <p>
            <%= link_to comment.user.name, mypage_path(@code.user.id), method: :get, class: "code-mypage-btn" %>:
            <%= comment.text %>
          </p>
        <% end %>
      </div>
      <%=link_to 'もどる', root_path, class:"root-back-button" %>
  <div>
    <audio autoplay src="https://res.cloudinary.com/dr47riclr/video/upload/v1628738609/music/Gm3_jdfb5p.mp3"></audio>
  </div>

app/views/messages/_main_chat.html.erb
<div class="chat-header">
  <div class="left-header">
    <div class="header-title">
      <%= @name %>
    </div>
  </div>
  <div class="right-header">
    <div class="header-button">
    <%= link_to "Dmを終了する", room_path(@room), method: :delete %>
    </div>
  </div>
</div>

<div class="messages">
  <%= render partial: 'message', collection: @messages %>
</div>

 <%= form_with model: [@room, @message], class: 'form', local: true do |f| %>
  <div class="form-input">
    <%= f.text_field :content, class: 'form-message', placeholder: 'メッセージを入力...' %>
    <label class="form-image">
      <span class="image-file">＋</span>
      <%= f.file_field :image, class: 'hidden' %>
    </label>
  </div>
  <%= f.submit '送信', class: 'form-submit' %>
<% end %>

app/views/messages/_message.html.erb
<div class="message">
  <div class="upper-message">
    <div class="message-user">
      <%= message.user.name %>
    </div>
    <div class="message-date">
      <%= l message.created_at %>
    </div>
  </div>
  <div class="lower-message">
    <div class="message-content">
      <%= message.content %>
    </div>
    <%= image_tag message.image.variant(resize: '300x300'), class: 'message-image' if message.image.attached? %>
  </div>
  <audio autoplay src="https://res.cloudinary.com/dr47riclr/video/upload/v1629873142/music/Dm_Code5_mb1tb6.mp3"></audio>
</div>

app/views/messages/_side_bar.html.erb
<div class="side-bar-header">
  <div class="header-name">
   <%= link_to current_user.name, root_path %>
  </div>
  <div class="create-room">
    <%= link_to "ルームを作成する", new_room_path %>
  </div>
</div>

<div class="rooms">
<% current_user.rooms.each do |room| %>
    <div class="room">
      <div class="room-name">
        <%= link_to @name, room_messages_path(room.id) %>
      </div>
    </div>
  <% end %>
</div>

app/views/messages/index.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "side_bar" %>
  </div>
  <div class="chat">
    <%= render "main_chat" %>
      <audio autoplay src="https://res.cloudinary.com/dr47riclr/video/upload/v1629117741/music/Dm_Code2_fp8zva.mp3"></audio>
   </div>
</div>

app/views/mypages/show.html.erb
<%= render "devise/shared/header" %>

<div class="contents-page">
  
  <%= render "profiles/show" %>

  <div class="content-page"><%= @name %>さんのコーデ一覧</div>

  <% @codes.each do |code| %>

  <%= link_to code_path(code.id) do %>

    <div class="content_post">
    <%= image_tag code.image, class: "code-img" if code.image.attached? %>
    <% end %>
    <div class="code-explain-box">＜コーデタイトル＞
      <%= simple_format code.code_title %>
    </div>
    <div class="code-explain-box">＜メッセージ＞
      <%= simple_format code.message %>
    </div>
    <div class="code-explain-box">＜着用ブランド＞
      <%= simple_format code.brand_name %>
    </div>
  <% end %>
    <%=link_to 'もどる', root_path, class:"root-back-button" %>
    <%=link_to 'Dm', new_room_path, class:"messages-button" if current_user.id != @id %>
    <%=link_to "編集", edit_profile_path , class: 'edit-profile' if current_user.id == @id %>
   <div>
    <audio autoplay src="https://res.cloudinary.com/dr47riclr/video/upload/v1629117741/music/Gm_Code2_zbd0rl.mp3"></audio>
  </div>
</div>

app/views/profiles/_show.html.erb
<% content_for(:title, 'プロフィール') %>
<div class="profiles">
  <div class="row">
    
      <h1> <%= "プロフィール" %></h1>
    <div class="profile-table">
      <table class="table">
        <tbody>
          <tr>
            <th class="table-list">名前</th>
              <td class ="table-form"><%= @name %></td>
          </tr>
          <tr>
            <th class="table-list">誕生日</th>
              <td class ="table-form"><%= @birthday %></td>
          </tr>
          <tr>
            <th class="table-list">好きなブランド</th>
              <td class ="table-form"><%= @favorite_brand %></td>
          </tr>
            <th class="table-list">自己紹介</th>
              <td class ="table-form-comment"><%= @comment %></td>
          </tr>
          <div class = "sns-link">
          <ul class="profile-links">
            <% if @twitter.present? %>
              <li class="profile-link">
                <%= link_to @twitter, target: :_blank do %>
                  <i class="fab fa-twitter-square"></i>
                <% end %>
              </li>
            <% end %>
            <% if @instagram.present? %>
              <li class="profile-link">
                <%= link_to @instagram, target: :_blank do %>
                  <i class="fab fa-instagram"></i>
                <% end %>
              </li>
            <% end %>
            </ul>
        </div>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/profiles/edit.html.erb
<% content_for(:title, 'プロフィール') %>
<div class="profiles">
  <div class="row">
  
      <h1><%= 'プロフィール編集' %></h1>
    <div class="profile-lists">
      <%= form_with model: @user, url: profile_path, local: true do |f| %>
        <%= render 'devise/shared/error_messages', model: f.object %>

        <div><%= f.label :名前 %></div>
          <div><%= f.text_field :name, class: "form-control" %></div>

         <div><%= f.label :誕生日 %></div>
          <div><%= f.text_field :birthday, class: "form-control" %></div>
       
        <div><%= f.label :好きなブランド %></div>
          <div><%= f.text_field :favorite_brand, class: "form-control" %></div>
        
        <div><%= f.label :自己紹介 %><div>
          <div><%= f.text_field :comment, class: "form-control" %></div>

        <div><%= f.label :twitter, 'Twitter URL' %></div>
          <div><%= f.text_field :twitter, placeholder: "Twitter URL", class: "form-control" %></div>

        <div><%= f.label :instagram, 'Instagram URL' %></div>
          <div><%= f.text_field :instagram, placeholder: "Instagram URL", class: "form-control" %></div>

        <%= f.submit '完了', class: "primary"%>
      <% end %>  
    </div>
  </div>
  <audio autoplay src="https://res.cloudinary.com/dr47riclr/video/upload/v1629873142/music/Gm_Code5_yzjui6.mp3"></audio>
</div>

app/views/rooms/index.html.erb
<div class='wrapper'>
  <div class='side-bar'>
    <%= render "messages/side_bar" %>
  </div>
  <audio autoplay src="https://res.cloudinary.com/dr47riclr/video/upload/v1629873142/music/Dm_Code3_bmyizj.mp3"></audio>
</div>

app/views/rooms/new.html.erb
<div class='chat-room-form'>
  <h1>新規チャットルーム</h1>
  <%=form_with model: @room, local: true do |f|%>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--right'>
       <select name="room[user_ids][]">
          <option value=""></option>
         <% User.where.not(id: current_user.id).each do |user| %>
            <option value=<%= user.id %>><%= user.name %></option>
          <% end %> 
        </select>
        <input name="room[user_ids][]" type="hidden" value=<%= current_user.id %>>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right'>
        <%= f.submit class: 'chat-room-form__action-btn'%>
      </div>
    </div>
  <% end %>
  <%=link_to 'もどる', root_path, class:"root-back-button" %>
  <%=link_to 'すすむ', rooms_path, class:"enter-button" %>
  <audio autoplay src="https://res.cloudinary.com/dr47riclr/video/upload/v1629873142/music/Dm_Code4_qfchvo.mp3"></audio>
</div>